
Inactive Modules:
  1) netcdf/4.8.1     2) openmpi/4.1.1

Due to MODULEPATH changes, the following have been reloaded:
  1) ncarcompilers/0.5.0

The following have been reloaded with a version change:
  1) intel/19.1.1 => intel/18.0.5


Inactive Modules:
  1) netcdf/4.8.1     2) openmpi/4.1.1

Due to MODULEPATH changes, the following have been reloaded:
  1) ncarcompilers/0.5.0

The following have been reloaded with a version change:
  1) intel/19.1.1 => intel/18.0.5


Inactive Modules:
  1) netcdf/4.8.1     2) openmpi/4.1.1

Due to MODULEPATH changes, the following have been reloaded:
  1) ncarcompilers/0.5.0

The following have been reloaded with a version change:
  1) intel/19.1.1 => intel/18.0.5


Inactive Modules:
  1) netcdf/4.8.1     2) openmpi/4.1.1

Due to MODULEPATH changes, the following have been reloaded:
  1) ncarcompilers/0.5.0

The following have been reloaded with a version change:
  1) intel/19.1.1 => intel/18.0.5

Traceback (most recent call last):
  File "compute_daily_CLM_averages.py", line 133, in <module>
    clm_output += read_pfb(f'{path_outputs}{runname}.out.clm_output.{timestamp_reading}.C.pfb')
  File "/glade/work/tijerina/conda-envs/parflow-npl/lib/python3.7/site-packages/parflow/tools/io.py", line 85, in read_pfb
    with ParflowBinaryReader(file, read_sg_info=read_sg_info) as pfb:
  File "/glade/work/tijerina/conda-envs/parflow-npl/lib/python3.7/site-packages/parflow/tools/io.py", line 392, in __init__
    self.f = open(self.filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/glade/scratch/tijerina/CONUS2/spinup_WY2003/run_inputs/spinup.wy2003.out.clm_output.08761.C.pfb'
